### ISSUE TITLE
Step 1. Culverts Issue

### ISSUE THREAD

**Issue by AshlandCountyLWCDGIS** [dnrwaterqualitymodeling/EVAAL#11]
I am unable to add a layer into the Step 1. Culverts section of the new EVAAL 1.2 update.

![image](https://user-images.githubusercontent.com/30264281/28320670-d13cd950-6b96-11e7-8c62-caef375a56ad.png)
Adding data from the radio button, ALL files are empty on this option. ArcCatalog is open to show that the layer in the "Look up" folder selected is in that folder. 

![image](https://user-images.githubusercontent.com/30264281/28320748-faab920e-6b96-11e7-8e3a-948f2c8cdc06.png)
Adding data by the drag and drop option and subsequent error message.

I completed many successful EVAAL runs with the 1.1. I am not sure what is restricting me from adding a layer into this culvert section.

**Comment by asruesch** [comment]
It looks like you are trying to add the culverts layer as a point feature class. The culvert layer must be a line feature class. Try creating a line feature class to ensure that that is indeed the problem. If that is indeed the problem, refer to Appendix A in the tutorial for how to create the culvert layer:

https://github.com/dnrwaterqualitymodeling/EVAAL/blob/master/doc/EVAAL_Tutorial_v1_0_JUN2017.pdf
