### ISSUE TITLE
Toolbox installation fails on ArcGIS 10.1

### ISSUE THREAD

**Issue by danswick** [dnrwaterqualitymodeling/EVAAL#3]
Attempting to install the tool on ArcMap 10.1 (build 3143) yields an arctoolbox icon with a red X over it. Opening the tool does not throw an error. 

![image](https://cloud.githubusercontent.com/assets/2365503/3801743/906f5b8c-1c07-11e4-8303-4a74de0dfa76.png)

**Comment by danswick** [comment]
Sorry for the long response on this. Your update fixed the issue. Marking this as closed. Thanks!

*aside*: Since testing this, I have updated to 10.2., though we still have some 10.1 licenses floating around if more cross-version testing is needed.

**Comment by asruesch** [comment]
Thanks for the update, Dan!
